project:
  uuid: 7a74dd32-05a3-449b-a764-f36d6bdbfcc0
  slug: solar
  node_id: ae2cabaccf16
  build_id: a8bf8607-cc8f-51cc-98c4-6c2375f6bdc3
mission_type_activations:
- software-dev
- documentation
- research
- plan
vcs:
  type: git
agents:
  available:
  - claude
  auto_commit: true
  lint_on_edit: false
